### ISSUE TITLE
Error: <!DOCTYPE html>

### ISSUE THREAD

**Issue by Xottab-DUTY** [AButler/upload-release-assets#21]
I'm getting really strange behaviour: unknown (for me) error happens and it outputs an HTML page source as an error description.

Log: https://github.com/OpenXRay/xray-16/actions/runs/4208583295/jobs/7304755158

**Comment by AButler** [comment]
This looks like the GitHub error page - GitHub looks to have had an incident at the time where it's APIs werent' responding. If this is still occuring please feel free to raise the issue again but I'm going to close as this is an issue outside of the action's control.
